# Generated by Django 3.2.9 on 2022-06-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=50)),
                ('companygstno', models.CharField(max_length=50)),
                ('hrmfname', models.CharField(max_length=50)),
                ('hrmlname', models.CharField(max_length=50)),
                ('dateofbirth', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('empid', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('jobdescription', models.CharField(max_length=50)),
            ],
        ),
    ]
