# Generated by Django 3.2.9 on 2022-06-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='applyjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('dateofbirth', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('percentage', models.CharField(max_length=50)),
                ('skills', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('contactno', models.CharField(max_length=50)),
                ('jonid', models.CharField(max_length=50)),
                ('projectdetails', models.CharField(max_length=50)),
            ],
        ),
    ]
